name: Rollback Tenant

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Region'
        required: true
        type: choice
        options:
          - us
          - uk
          - eu
      cluster:
        description: 'Select Cluster'
        required: true
        type: choice
        options:
          - primary-01
          - primary-02
          - satellite-01
      tenant:
        description: 'Tenant ID'
        required: true
      app:
        description: 'App to rollback'
        required: true
        type: choice
        options:
          - tenant-api
          - tenant-app
          - tenant-dragonfly
      commit_to_revert:
        description: 'Commit SHA to revert to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: yousmakhayyam/Apporto-demo-k8s-gitops
          token: ${{ secrets.GITOPS_PAT }}
          fetch-depth: 0

      - name: Revert Commit
        run: |
          git revert --no-commit ${{ inputs.commit_to_revert }}..HEAD
          FILE="tenants/${{ inputs.region }}/${{ inputs.cluster }}/${{ inputs.tenant }}/${{ inputs.app }}/values.yaml"
          git add $FILE
          git commit -m "rollback: region-${{ inputs.region }} cluster-${{ inputs.cluster }} tenant-${{ inputs.tenant }} app-${{ inputs.app }}"
          git push origin main