name: Update Resources

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Region'
        required: true
        type: choice
        options:
          - us
          - uk
          - eu
      cluster:
        description: 'Select Cluster'
        required: true
        type: choice
        options:
          - primary-01
          - primary-02
          - satellite-01
      tenant:
        description: 'Tenant ID'
        required: true
      app:
        description: 'App to update'
        required: true
        type: choice
        options:
          - tenant-api
          - tenant-app
          - tenant-dragonfly
      memory:
        description: 'Memory Limit (e.g., 2Gi, 4Gi)'
        required: true
        default: '2Gi'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: yousmakhayyam/Apporto-demo-k8s-gitops
          token: ${{ secrets.GITOPS_PAT }}

      - name: Update Memory
        run: |
          FILE="tenants/${{ inputs.region }}/${{ inputs.cluster }}/${{ inputs.tenant }}/${{ inputs.app }}/values.yaml"
          yq eval '.resources.limits.memory = "${{ inputs.memory }}"' $FILE -i
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add $FILE
          git commit -m "resource: region-${{ inputs.region }} cluster-${{ inputs.cluster }} tenant-${{ inputs.tenant }} app-${{ inputs.app }} memory to ${{ inputs.memory }}"
          git push origin main